<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\yummy-red-1.0.0\assets\.DS_Store" />
    <None Include="wwwroot\yummy-red-1.0.0\assets\img\.DS_Store" />
    <None Include="wwwroot\yummy-red-1.0.0\assets\vendor\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
  </ItemGroup>

</Project>
